version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/phytodb
    networks:
      - phyto-network

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app       
      - /app/node_modules              
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    networks:
      - phyto-network


  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: phytodb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - phyto-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@phyto.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - phyto-network

volumes:
  pgdata:
  pgadmin-data:

networks: 
  phyto-network:
    driver: bridge 